### ISSUE TITLE
crash-report Valkyrien Warfare 0.9_pre_1.jar

### ISSUE THREAD

**Issue by le10077** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#102]
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at ValkyrienWarfareBase.PhysicsManagement.PhysicsTickHandler.onWorldTickStart(PhysicsTickHandler.java:37)
	at ValkyrienWarfareBase.EventsCommon.onTickEvent(EventsCommon.java:110)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_496_EventsCommon_onTickEvent_TickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:282)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:694)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by Best108** [comment]
Old issue, closed.
