### ISSUE TITLE
NullPointerException in PhysicsTickHandler

### ISSUE THREAD

**Issue by zedwick** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#131]
Running Valkyrien+Warfare+0.9_pre_3+[HotFix]

See the below error in console irregularly, but frequently (several times a minute).

```
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at valkyrienwarfare.physics.management.PhysicsTickHandler.onWorldTickEnd(PhysicsTickHandler.java:102)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at valkyrienwarfare.mod.event.EventsCommon.onTickEvent(EventsCommon.java:213)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_56_EventsCommon_onTickEvent_TickEvent.invoke(.dynamic)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:774)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at java.lang.Thread.run(Thread.java:748)
[01:30:49] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at valkyrienwarfare.physics.management.PhysicsTickHandler.onWorldTickEnd(PhysicsTickHandler.java:102)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at valkyrienwarfare.mod.event.EventsCommon.onTickEvent(EventsCommon.java:213)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_56_EventsCommon_onTickEvent_TickEvent.invoke(.dynamic)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:774)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
[01:30:49] [Server thread/INFO] [STDERR]: [valkyrienwarfare.physics.management.PhysicsTickHandler:onWorldTickEnd:104]: 	at java.lang.Thread.run(Thread.java:748)
[01:30:49] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
```

**Comment by Best108** [comment]
Old issue, closed.
