### ISSUE TITLE
VW doesn't like comparators with chests

### ISSUE THREAD

**Issue by LightningSh0ck** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#152]
NOTE: I just upgraded on latest development of this time and I'm not sure if master does this as well, but if I remember correctly it doesn't. I've also re-tested this on a fresh world.

Having a comparator with a chest attached will not infuse and throws an error:
```
 Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.World.func_175647_a(World.java:4273) ~[amu.class:?]
	at net.minecraft.world.World.func_72872_a(World.java:3060) ~[amu.class:?]
	at net.minecraft.block.BlockChest.func_176453_o(BlockChest.java:546) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_176457_m(BlockChest.java:536) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_189418_a(BlockChest.java:460) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_180676_d(BlockChest.java:444) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_180641_l(BlockChest.java:566) ~[api.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185888_a(BlockStateContainer.java:398) ~[awu$a.class:?]
	at net.minecraft.block.BlockRedstoneComparator.func_176397_f(BlockRedstoneComparator.java:136) ~[app.class:?]
	at net.minecraft.block.BlockRedstoneComparator.func_176460_j(BlockRedstoneComparator.java:97) ~[app.class:?]
	at net.minecraft.block.BlockRedstoneComparator.func_176398_g(BlockRedstoneComparator.java:195) ~[app.class:?]
	at net.minecraft.block.BlockRedstoneDiode.func_189540_a(BlockRedstoneDiode.java:108) ~[apw.class:?]
	at net.minecraft.block.BlockRedstoneComparator.onNeighborChange(BlockRedstoneComparator.java:327) ~[app.class:?]
	at net.minecraft.world.World.func_175666_e(World.java:3808) ~[amu.class:?]
	at net.minecraft.tileentity.TileEntity.func_70296_d(TileEntity.java:163) ~[avj.class:?]
	at valkyrienwarfare.physics.management.PhysicsObject.assembleShip(PhysicsObject.java:495) ~[PhysicsObject.class:?]
	at valkyrienwarfare.physics.management.PhysicsObject.processChunkClaims(PhysicsObject.java:274) ~[PhysicsObject.class:?]
	at valkyrienwarfare.physics.management.PhysicsWrapperEntity.<init>(PhysicsWrapperEntity.java:73) ~[PhysicsWrapperEntity.class:?]
	at valkyrienwarfare.mod.block.BlockPhysicsInfuser.func_180639_a(BlockPhysicsInfuser.java:66) ~[BlockPhysicsInfuser.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:446) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.redirect$handleUseItemPacket$zzk000(SourceFile:566) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```
If you put ONLY a chest w/ a comp and infuse that, the ship infuses, disappears and it only outputs this:

Tried to add entity valkyrienwarfare:physwrapper but it was marked as removed already

I've tried replicating this with a budded anvil(as I've thought it is because of the comparator being budded) but no, it works fine.

One can instead build it on an already built ship, and it will stay like that, unless you have a block that checks for redstone power upon loading(my thruster that I'm working on), which will disappear and throw yet another error:
```
 [Server thread/ERROR] [FML]: An Entity valkyrienwarfare:physwrapper(LightningShock:13) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
net.minecraft.util.ReportedException: Loading entity NBT
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1875) ~[vg.class:?]
	at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:221) [vi.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186053_a(AnvilChunkLoader.java:601) [aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186050_a(AnvilChunkLoader.java:528) [aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:485) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:97) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) [on.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.World.func_175647_a(World.java:4273) ~[amu.class:?]
	at net.minecraft.world.World.func_72872_a(World.java:3060) ~[amu.class:?]
	at net.minecraft.block.BlockChest.func_176453_o(BlockChest.java:546) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_176457_m(BlockChest.java:536) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_189418_a(BlockChest.java:460) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_180676_d(BlockChest.java:444) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_180641_l(BlockChest.java:566) ~[api.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185888_a(BlockStateContainer.java:398) ~[awu$a.class:?]
	at net.minecraft.block.BlockRedstoneComparator.func_176397_f(BlockRedstoneComparator.java:136) ~[app.class:?]
	at net.minecraft.block.BlockRedstoneComparator.func_176460_j(BlockRedstoneComparator.java:97) ~[app.class:?]
	at net.minecraft.block.BlockRedstoneComparator.func_176398_g(BlockRedstoneComparator.java:195) ~[app.class:?]
	at net.minecraft.block.BlockRedstoneDiode.func_189540_a(BlockRedstoneDiode.java:108) ~[apw.class:?]
	at net.minecraft.block.BlockRedstoneComparator.onNeighborChange(BlockRedstoneComparator.java:327) ~[app.class:?]
	at net.minecraft.world.World.func_175666_e(World.java:3808) ~[amu.class:?]
	at net.minecraft.tileentity.TileEntity.func_70296_d(TileEntity.java:163) ~[avj.class:?]
	at zmaster587.libVulpes.tile.multiblock.TileMultiBlock.completeStructure(TileMultiBlock.java:408) ~[TileMultiBlock.class:unspecified]
	at spaceengineering.tile.multiblock.TileLiquidFuelThruster.onLoad(TileLiquidFuelThruster.java:153) ~[TileLiquidFuelThruster.class:?]
	at net.minecraft.world.World.func_175700_a(World.java:1918) ~[amu.class:?]
	at net.minecraft.world.World.func_147448_a(World.java:1945) ~[amu.class:?]
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:854) ~[axw.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:105) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:309) ~[amu.class:?]
	at valkyrienwarfare.physics.management.PhysicsObject.loadClaimedChunks(PhysicsObject.java:752) ~[PhysicsObject.class:?]
	at valkyrienwarfare.physics.management.PhysicsObject.readFromNBTTag(PhysicsObject.java:938) ~[PhysicsObject.class:?]
	at valkyrienwarfare.physics.management.PhysicsWrapperEntity.func_70037_a(PhysicsWrapperEntity.java:222) ~[PhysicsWrapperEntity.class:?]
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1863) ~[vg.class:?]
	... 14 more
```
Funny enough I couldn't reproduce these with a dropper.

While I am at it, I also can't infuse my thruster multiblock if it is completed:
```
[Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.particle.ParticleManager.handler$preAddEffect$zbe000(ParticleManager.java:602) ~[btg.class:?]
	at net.minecraft.client.particle.ParticleManager.func_78873_a(ParticleManager.java) ~[btg.class:?]
	at zmaster587.libVulpes.client.ClientProxy.spawnParticle(ClientProxy.java:45) ~[ClientProxy.class:unspecified]
	at zmaster587.libVulpes.tile.multiblock.TileMultiBlock.completeStructure(TileMultiBlock.java:354) ~[TileMultiBlock.class:unspecified]
	at spaceengineering.tile.multiblock.TileLiquidFuelThruster.onLoad(TileLiquidFuelThruster.java:153) ~[TileLiquidFuelThruster.class:?]
	at net.minecraft.world.World.func_175700_a(World.java:1918) ~[amu.class:?]
	at net.minecraft.world.World.func_175690_a(World.java:4401) ~[amu.class:?]
	at valkyrienwarfare.physics.management.PhysicsObject.assembleShip(PhysicsObject.java:488) ~[PhysicsObject.class:?]
	at valkyrienwarfare.physics.management.PhysicsObject.processChunkClaims(PhysicsObject.java:274) ~[PhysicsObject.class:?]
	at valkyrienwarfare.physics.management.PhysicsWrapperEntity.<init>(PhysicsWrapperEntity.java:73) ~[PhysicsWrapperEntity.class:?]
	at valkyrienwarfare.mod.block.BlockPhysicsInfuser.func_180639_a(BlockPhysicsInfuser.java:66) ~[BlockPhysicsInfuser.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:446) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.redirect$handleUseItemPacket$zzk000(SourceFile:566) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

```

**Comment by Best108** [comment]
Old issue, closed.
