### ISSUE TITLE
MASSIVE log spam

### ISSUE THREAD

**Issue by DeltaNedas** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#281]
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: java.lang.Exception: Tried getting entities from giant bounding box of box[-19.421859910811204, 0.0, -7.591574555424993 -> 20.578140089188796, 200.0, 32.40842544457501]
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.world.World.func_175674_a(World.java:5837)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.world.World.func_72839_b(World.java:3006)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at micdoodle8.mods.galacticraft.core.client.model.ModelBipedGC.setRotationAngles(ModelBipedGC.java:120)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.model.ModelBiped.func_78087_a(SourceFile:259)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.model.ModelPlayer.func_78087_a(ModelPlayer.java:126)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.model.ModelBiped.func_78088_a(SourceFile:79)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.model.ModelPlayer.func_78088_a(ModelPlayer.java:75)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at micdoodle8.mods.galacticraft.core.client.model.ModelPlayerGC.func_78088_a(ModelPlayerGC.java:43)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.renderer.entity.RenderLivingBase.func_77036_a(RenderLivingBase.java:344)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:240)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:71)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:128)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:802)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[18:32:21] [Client thread/INFO] [STDERR]: [net.minecraft.world.World:func_175674_a:5837]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
this is spammed every tick, leading to a 14mb log.
tested in jenkins 460

**Comment by Rubyjunk** [comment]
Hi, thanks for your report. If possible, could you provide instructions for reproducing this issue?

**Comment by Rongmario** [comment]
I'm getting this issue too, with select mods that spawn mobs, this will happen as soon as you create a world, this only started happening on 0.9final.

[Log when playing with Champions](url)

Other mods such as Thaumcraft, EerieEntities, Primitive Mobs has similar errors spamming too.

**Comment by Rubyjunk** [comment]
Confirmed.

**Comment by Best108** [comment]
Fixed as of 552e0b9d238d3ba42bbec7a565c16688c99f1ff5

**Comment by DeltaNedas** [comment]
very based, thank you
