### ISSUE TITLE
"Invalid player move packet received" Error when using the ship helm

### ISSUE THREAD

**Issue by Umitrix** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#285]
When using the ship's helm you get this crash message.

**Comment by Umitrix** [comment]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2019-08-03 03:23:10 BST
Description: Exception ticking world

java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(Unknown Source)
    at java.util.HashMap$KeyIterator.next(Unknown Source)
    at net.minecraft.server.management.PlayerChunkMap.tick(PlayerChunkMap.java:180)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227)
    at net.optifine.override.WorldServerOF.tick(WorldServerOF.java:39)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: New World231
  All players: 1 total; [GCEntityPlayerMP['Kalizy'/1140, l='New World231', x=-51.99, y=75.44, z=-33.88]]
  Chunk stats: ServerChunkCache: 1539 Drop: 0
  Level seed: -3468574139879553671
  Level generator: ID 00 - default, ver 1. Features enabled: true
  Level generator options: 
  Level spawn location: World: (-184,64,256), Chunk: (at 8,4,0 in -12,16; contains blocks -192,0,256 to -177,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 46180 game time, 46180 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 99010 (now: false), thunder time: 12275 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_221, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 12449279784 bytes (11872 MB) / 15032385536 bytes (14336 MB) up to 15032385536 bytes (14336 MB)
  JVM Flags: 5 total; -Xms14336m -Xmx14336m -XX:+UseG1GC -XX:MaxGCPauseMillis=4 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
  FML: MCP 9.42 Powered by Forge 14.23.5.2824 Optifine OptiFine_1.12.2_HD_U_E3 137 mods loaded, 137 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                   | Version           | Source                                                    | Signature                                |
       |:------ |:------------------------------------ |:----------------- |:--------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                            | 1.12.2            | minecraft.jar                                             | None                                     |
       | LCHIJA | mcp                                  | 9.42              | minecraft.jar                                             | None                                     |
       | LCHIJA | FML                                  | 8.0.99.99         | modpack.jar                                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                                | 14.23.5.2824      | modpack.jar                                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy                    | 1.0.0             | minecraft.jar                                             | None                                     |
       | LCHIJA | ivtoolkit                            | 1.3.3-1.12        | minecraft.jar                                             | None                                     |
       | LCHIJA | littletilescore                      | 1.0.0             | minecraft.jar                                             | None                                     |
       | LCHIJA | micdoodlecore                        |                   | minecraft.jar                                             | None                                     |
       | LCHIJA | smoothfontcore                       | mc1.12.2-2.0      | minecraft.jar                                             | None                                     |
       | LCHIJA | openmodscore                         | 0.12.2            | minecraft.jar                                             | None                                     |
       | LCHIJA | foamfixcore                          | 7.7.4             | minecraft.jar                                             | None                                     |
       | LCHIJA | srm-hooks                            | 1.12.2-1.0.0      | minecraft.jar                                             | None                                     |
       | LCHIJA | randompatches                        | 1.12.2-1.16.3.1   | randompatches-1.12.2-1.16.3.1.jar                         | None                                     |
       | LCHIJA | smoothfont                           | mc1.12.2-2.0      | SmoothFont-mc1.12.2-2.0.jar                               | None                                     |
       | LCHIJA | baubles                              | 1.5.2             | Baubles-1.12-1.5.2.jar                                    | None                                     |
       | LCHIJA | jei                                  | 4.15.0.285        | jei_1.12.2-4.15.0.285.jar                                 | None                                     |
       | LCHIJA | botania                              | r1.10-361         | Botania+r1.10-361.jar                                     | None                                     |
       | LCHIJA | redstoneflux                         | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar                   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cofhcore                             | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar                    | None                                     |
       | LCHIJA | craftstudioapi                       | 1.0.0             | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar        | None                                     |
       | LCHIJA | mantle                               | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                                  | None                                     |
       | LCHIJA | natura                               | 1.12.2-4.3.2.69   | natura-1.12.2-4.3.2.69.jar                                | None                                     |
       | LCHIJA | harvestcraft                         | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zd+Surprise+for+Yogcast.jar      | None                                     |
       | LCHIJA | ctm                                  | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                                 | None                                     |
       | LCHIJA | twilightforest                       | 3.8.689           | twilightforest-1.12.2-3.8.689-universal.jar               | None                                     |
       | LCHIJA | animania                             | 1.6.2             | animania-1.12.2-1.6.2.jar                                 | None                                     |
       | LCHIJA | appleskin                            | 1.0.9             | AppleSkin-mc1.12-1.0.9.jar                                | None                                     |
       | LCHIJA | appliedenergistics2                  | rv6-stable-6      | appliedenergistics2-rv6-stable-6.jar                      | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHIJA | backpack                             | 3.0.2             | backpack-3.0.2-1.12.2.jar                                 | None                                     |
       | LCHIJA | ichunutil                            | 7.2.1             | iChunUtil-1.12.2-7.2.1.jar                                | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | backtools                            | 7.0.0             | BackTools-1.12.2-7.0.0.jar                                | None                                     |
       | LCHIJA | bno                                  | 1.12.2-1.0.4.0    | BasicNetherOres-1.12.2-1.0.4.0.jar                        | None                                     |
       | LCHIJA | battletowers                         | 1.6.4             | BattleTowers-1.12.2_1.6.4.jar                             | None                                     |
       | LCHIJA | forgelin                             | 1.8.3             | Forgelin-1.8.3.jar                                        | None                                     |
       | LCHIJA | betterportals                        | 0.1.6             | betterportals-0.1.6.jar                                   | None                                     |
       | LCHIJA | bibliocraft                          | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                         | None                                     |
       | LCHIJA | bookshelf                            | 2.3.585           | Bookshelf-1.12.2-2.3.585.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | buildcraftlib                        | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                              | None                                     |
       | LCHIJA | buildcraftcore                       | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                              | None                                     |
       | LCHIJA | buildcraftbuilders                   | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                              | None                                     |
       | LCHIJA | buildcrafttransport                  | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                              | None                                     |
       | LCHIJA | buildcraftsilicon                    | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                              | None                                     |
       | LCHIJA | crafttweaker                         | 4.1.19            | CraftTweaker2-1.12-4.1.19.jar                             | None                                     |
       | LCHIJA | buildcraftcompat                     | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                              | None                                     |
       | LCHIJA | buildcraftenergy                     | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                              | None                                     |
       | LCHIJA | buildcraftfactory                    | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                              | None                                     |
       | LCHIJA | buildcraftrobotics                   | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                              | None                                     |
       | LCHIJA | cctweaked                            | 1.83.1            | cc-tweaked-1.12.2-1.83.1.jar                              | None                                     |
       | LCHIJA | computercraft                        | 1.83.1            | cc-tweaked-1.12.2-1.83.1.jar                              | None                                     |
       | LCHIJA | chesttransporter                     | 2.8.8             | ChestTransporter-1.12.2-2.8.8.jar                         | None                                     |
       | LCHIJA | chisel                               | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                              | None                                     |
       | LCHIJA | chococraft                           | 0.9.8.0           | chococraft_1.12.2-0.9.8.0.jar                             | None                                     |
       | LCHIJA | codechickenlib                       | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar             | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | cofhworld                            | 1.3.1             | CoFHWorld-1.12.2-1.3.1.7-universal.jar                    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cosmeticarmorreworked                | 1.12.2-v4         | CosmeticArmorReworked-1.12.2-v4.jar                       | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | cosmeticarmorreworked|tombmanygraves | 1.12.2-v4         | CosmeticArmorReworked-1.12.2-v4.jar                       | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | ctgui                                | 1.0.0             | CraftTweaker2-1.12-4.1.19.jar                             | None                                     |
       | LCHIJA | crafttweakerjei                      | 2.0.3             | CraftTweaker2-1.12-4.1.19.jar                             | None                                     |
       | LCHIJA | creativecore                         | 1.9.9             | CreativeCore_v1.9.45_mc1.12.2.jar                         | None                                     |
       | LCHIJA | custommainmenu                       | 2.0.8             | CustomMainMenu-MC1.12.2-2.0.8.jar                         | None                                     |
       | LCHIJA | defaultoptions                       | 9.2.8             | DefaultOptions_1.12.2-9.2.8.jar                           | None                                     |
       | LCHIJA | dimdoors                             | 3.0.9+287         | DimensionalDoors-3.0.9-287.jar                            | None                                     |
       | LCHIJA | ding                                 | 1.0.1             | Ding-1.12.1-1.0.1.jar                                     | None                                     |
       | LCHIJA | dungeontactics                       | DT-0.16.5         | DungeonTactics-1.12.2-0.16.5.jar                          | None                                     |
       | LCHIJA | durabilityshow                       | 5.0.0             | Durability+Show-1.12-5.0.0.jar                            | None                                     |
       | LCHIJA | eplus                                | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | enchdesc                             | 1.1.15            | EnchantmentDescriptions-1.12.2-1.1.15.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | endercore                            | 1.12.2-0.5.59     | EnderCore-1.12.2-0.5.59.jar                               | None                                     |
       | LCHIJA | thermalfoundation                    | 2.6.3             | ThermalFoundation-1.12.2-2.6.3.27-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalexpansion                     | 5.5.4             | ThermalExpansion-1.12.2-5.5.4.43-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | enderio                              | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
       | LCHIJA | enderiointegrationtic                | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
       | LCHIJA | enderiobase                          | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
       | LCHIJA | enderioconduits                      | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
       | LCHIJA | enderioconduitsappliedenergistics    | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
       | LCHIJA | enderioconduitsopencomputers         | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
       | LCHIJA | enderioconduitsrefinedstorage        | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
       | LCHIJA | enderiointegrationforestry           | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
       | LCHIJA | tconstruct                           | 1.12.2-2.12.0.157 | TConstruct-1.12.2-2.12.0.157.jar                          | None                                     |
       | LCHIJA | enderiointegrationticlate            | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
       | LCHIJA | enderiomachines                      | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
       | LCHIJA | enderiopowertools                    | 5.0.46            | EnderIO-1.12.2-5.0.46.jar                                 | None                                     |
       | LCHIJA | enderstorage                         | 2.4.5.135         | EnderStorage-1.12.2-2.4.5.135-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | energyconverters                     | 1.3.0.15          | energyconverters_1.12.2-1.3.0.15.jar                      | None                                     |
       | LCHIJA | extrautils2                          | 1.0               | extrautils2-1.12-1.9.9.jar                                | None                                     |
       | LCHIJA | featuredservers                      | 1.12-1.0.6        | FeaturedServers-1.12-1.0.6.jar                            | None                                     |
       | LCHIJA | foamfix                              | 0.10.5-1.12.2     | foamfix-0.10.5-1.12.2.jar                                 | None                                     |
       | LCHIJA | forgemultipartcbe                    | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar              | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | microblockcbe                        | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar              | None                                     |
       | LCHIJA | minecraftmultipartcbe                | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar              | None                                     |
       | LCHIJA | cfm                                  | 6.3.0             | furniture-6.3.0-1.12.2.jar                                | None                                     |
       | LCHIJA | ic2                                  | 2.8.1000          | IC2Classic+1.12-1.5.4.3.2.jar                             | None                                     |
       | LCHIJA | galacticraftcore                     | 4.0.2.210         | GalacticraftCore-1.12.2-4.0.2.210.jar                     | None                                     |
       | LCHIJA | galacticraftplanets                  | 4.0.2.210         | Galacticraft-Planets-1.12.2-4.0.2.210.jar                 | None                                     |
       | LCHIJA | grapplemod                           | 1.12.2-v11.1      | grapplemod-v11.1-1.12.2.jar                               | None                                     |
       | LCHIJA | helpfixer                            | 1.12.1-1.5.18     | HelpFixer-1.12.1-1.5.18.jar                               | None                                     |
       | LCHIJA | placebo                              | 1.5.1             | Placebo-1.12.2-1.5.1.jar                                  | None                                     |
       | LCHIJA | hexxitgear                           | 2.8.0             | Hexxit+Gear-1.12.2-2.8.0.jar                              | None                                     |
       | LCHIJA | waila                                | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                               | None                                     |
       | LCHIJA | ic2-classic-spmod                    | 0.0.0.0           | IC2Classic+1.12-1.5.4.3.2.jar                             | None                                     |
       | LCHIJA | teslacorelib                         | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | industrialforegoing                  | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.12.12-236.jar                | None                                     |
       | LCHIJA | infernalmobs                         | 1.7.6             | InfernalMobs-1.12.1.jar                                   | None                                     |
       | LCHIJA | ironchest                            | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.69.845.jar                           | None                                     |
       | LCHIJA | jrftl                                | 1.1               | JRFTL[1.12.2]-1.1.jar                                     | None                                     |
       | LCHIJA | littletiles                          | 1.5.0             | LittleTiles_v1.5.0-pre135_mc1.12.2.jar                    | None                                     |
       | LCHIJA | mcmultipart                          | 2.5.3             | MCMultiPart-2.5.3.jar                                     | None                                     |
       | LCHIJA | recipehandler                        | 0.13              | NoMoreRecipeConflict-0.13(1.12.2).jar                     | None                                     |
       | LCHIJA | openmods                             | 0.12.2            | OpenModsLib-1.12.2-0.12.2.jar                             | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | openblocks                           | 1.8.1             | OpenBlocks-1.12.2-1.8.1.jar                               | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | plasmaengines                        | 0.1               | PlasmaEngine-1.1.jar                                      | None                                     |
       | LCHIJA | quacklib                             | 2.2.5             | quacklib-2.2.5.jar                                        | None                                     |
       | LCHIJA | quickhomes                           | 1.2.2             | QuickHomes-1.2.2.jar                                      | None                                     |
       | LCHIJA | quickteleports                       | 1.1.0             | quickteleports-1.1.0.jar                                  | None                                     |
       | LCHIJA | railcraft                            | 12.0.0            | railcraft-12.0.0.jar                                      | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCHIJA | reccomplex                           | 1.4.8.2           | RecurrentComplex-1.4.8.2.jar                              | None                                     |
       | LCHIJA | redstonearsenal                      | 2.6.3             | RedstoneArsenal-1.12.2-2.6.3.18-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | redwoods                             | 1.2.1             | Redwoods-1.12-1.2.1.jar                                   | None                                     |
       | LCHIJA | reforged                             | 0.7.5             | Reforged-0.7.5-1.12+.jar                                  | None                                     |
       | LCHIJA | xreliquary                           | 1.12.2-1.3.4.786  | Reliquary-1.12.2-1.3.4.786.jar                            | None                                     |
       | LCHIJA | rswires                              | 1.0               | rswires-3.0.1.jar                                         | None                                     |
       | LCHIJA | secretroomsmod                       | 5.6.4             | secretroomsmod-1.12.2-5.6.4.jar                           | None                                     |
       | LCHIJA | thermaldynamics                      | 2.5.5             | ThermalDynamics-1.12.2-2.5.5.21-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | simplyjetpacks                       | 2.2.12.65         | SimplyJetpacks2-1.12.2-2.2.12.65.jar                      | None                                     |
       | LCHIJA | soulshardsrespawn                    | 1.12.2-1.1.0-12   | SoulShardsRespawn-1.12.2-1.1.0-12.jar                     | None                                     |
       | LCHIJA | torohealthmod                        | 1.12.2-11         | torohealth-1.12.2-11.jar                                  | None                                     |
       | LCHIJA | traverse                             | 1.6.0             | Traverse-1.12.2-1.6.0-69.jar                              | None                                     |
       | LCHIJA | bspkrscore                           | at_0.9            | Treecapitator-1.12-at_0.9a.jar                            | None                                     |
       | LCHIJA | treecapitator                        | at_0.9            | Treecapitator-1.12-at_0.9a.jar                            | None                                     |
       | LCHIJA | valkyrienwarfare                     | 0.9.2             | ValkyrienWarfareRevamped-1.12.2-0.9a-full-jenkins-461.jar | b308676914a5e7d99459c1d2fb298744387899a7 |
       | LCHIJA | vanillafix                           | 1.0.10-SNAPSHOT   | VanillaFix-1.0.10-99.jar                                  | None                                     |
       | LCHIJA | wanionlib                            | 1.12.2-2.2        | WanionLib-1.12.2-2.2.jar                                  | None                                     |
       | LCHIJA | xaerominimap                         | 1.17.4            | Xaeros_Minimap_1.17.4_Forge_1.12.jar                      | None                                     |
       | LCHIJA | xaeroworldmap                        | 1.4.3             | XaerosWorldMap_1.4.3_Forge_1.12.jar                       | None                                     |
       | LCHIJA | reauth                               | 3.6.0             | reauth-3.6.0.jar                                          | daba0ec4df71b6da841768c49fb873def208a1e3 |
       | LCHIJA | teslacorelib_registries              | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                          | None                                     |
       | LCHIJA | unidict                              | 1.12.2-2.9.2      | UniDict-1.12.2-2.9.2.jar                                  | None                                     |
  Loaded coremods (and transformers): LittlePatchingLoader (LittleTiles_v1.5.0-pre135_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      CreativePatchingLoader (CreativeCore_v1.9.45_mc1.12.2.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.59-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      CorePlugin (SmoothFont-mc1.12.2-2.0.jar)
                                        bre.smoothfont.asm.Transformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      ForgelinPlugin (Forgelin-1.8.3.jar)
                                        
                                      MixinLoaderForge (ValkyrienWarfareRevamped-1.12.2-0.9a-full-jenkins-461.jar)
                                        
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.210.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
                                        com.wynprice.secretroomsmod.core.SecretRoomsTransformer
                                      RandomPatches (randompatches-1.12.2-1.16.3.1.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      PluginLoader (MemoryTester-0.4.2.jar)
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced)
                               - NaturaOverworld (Enabled/Not Forced)
                               - NaturaNether (Enabled/Not Forced)
                               - NaturaDecorative (Enabled/Not Forced)
                               - NaturaTools (Enabled/Not Forced)
                               - NaturaEntities (Enabled/Not Forced)
                               - NaturaOredict (Enabled/Forced)
                               - NaturaWorld (Enabled/Not Forced)
  AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                              * Optifine is installed. This is NOT supported.
                             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  AE2 Integration: IC2:ON, RC:ON, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
  Suspected Mods: Unknown
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [GCEntityPlayerMP['Kalizy'/1140, l='New World231', x=-51.99, y=75.44, z=-33.88]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

This is on a heavily modded version of Minecraft, the crash happened when the ship hit one of the mod's trees

**Comment by zayats1** [comment]
Instal Vanillafix! For better  crash/bug reporting  if u use hastebin!
Use Holly Hastebin! F**k pastebin!

**Comment by Rubyjunk** [comment]
Hi, this looks like some sort of multithreading issue on our part. I will look into it. Thanks for your report.
